name: CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6.0.1

      - name: Run tests
        working-directory: .github/workflows/helpers/evaluate-automerge
        run: python3 -m unittest -v
